### ISSUE TITLE
What happened to the messages for "Check for updates"

### ISSUE THREAD

**Issue by bergware** [limetech/dynamix#113]
What exactly has been changed which causes no more messaging when the box is opened to show plugin updates ?

Is this intentional, because I see the remark for one of the internal unraid versions "to be less verbose" ?

As it stands now, it is confusing since it gives the user the impression nothing is happening, specially when there is a long list of plugins to be verified.

**Comment by jonpanozzo** [comment]
This is a bug.  Something isn’t working right.  I don’t know the details but will investigate next week with Eric to see what’s going on.

**Comment by limetech** [comment]
I was going to ask you the same thing :)

**Comment by bergware** [comment]
Fixed it
