### ISSUE TITLE
Remove "notify init" from rc.local

### ISSUE THREAD

**Issue by bergware** [limetech/dynamix#123]
On system start-up the command "notify init" is not required. It will try to chmod files which don't exist at that point in time.

Starting with only "notify smtp-init" is sufficient to have the notifications system initialized.

**Comment by limetech** [comment]
Is the 'notify init' command used somewhere else?  If not, we can leave the 'init' subcommand there as possible future hook, and make it's functionality in notify.php a "no-op".

**Comment by bergware** [comment]
Yes "notify init" is used by the browser upon first load of the page(s). This function is done to prevent already displayed notifications to be duplicated on a page refresh.

**Comment by bergware** [comment]
We can remove this, perhaps in 6.1 ?
