### ISSUE TITLE
Events triggered on power failed/power restored

### ISSUE THREAD

**Issue by PeterAOBell** [limetech/dynamix#128]
Would it be possible to generate events triggered by power failed/power restored, as detected/reported by apcupsd?

I have a process, impkemented as a plugin (pop mail fetcher), which I would prefer not to be launched if a shutdown is imminent.  Waiting for the events triggered by the actual shutdown is leaving it too late, and the plugin has to issue a kill -9 to ensure the process stops before the the array is stopped.

I'm sure that there will be other plugins which could benefit from being warned as soon as the power failure is detected.

**Comment by gfjardim** [comment]
You can use the ***stopping_svcs*** event to do that. If you need help making it work, please send me a PM.

**Comment by gfjardim** [comment]
PS: apparently, you can probe the UPS status using ***apcaccess status***; if your plugin run in a loop, you can check the UPS status before launching it.

**Comment by PeterAOBell** [comment]
I'm sure that the stopping_svds event doesn't occur until after the shutdown has been initiated, immediately before the array is stopped.

My pop plugin relies on crontab to launch the mpop binary every five minutes, fetching from several remote mailboxes.  If there are large emails (or lots of small ones), or one of the servers is slow to respond, the process can be active for several minutes.  I wouldn't want to stall an apcupsd-invoked power down for that long.

The only way I could overcome the problem would be to wrap the crontab job as a script, calling apcaccess every five minutes.

I guess that I need to look at what event scripts can be launched by apcupsd ... but it would be much nicer if this was built in to the system!

**Comment by gfjardim** [comment]
The problem I see is: emhttp_event is designed for emhttp. If every plugin trigger their own events, event system will start to be confused, specially when you realize not every one use every plugin. I don't have an APC UPS, so it won't work for me.

IMHO, you should point your cron job to a script that verifies the UPS status, aborting that cycle if the server is on backup power.
