### ISSUE TITLE
Disk status symbols

### ISSUE THREAD

**Issue by bergware** [limetech/dynamix#148]
Since the introduction of the new status symbols no real reactions/feedback was given until now.

See this post http://lime-technology.com/forum/index.php?topic=40209

I have made a proposal to introduce yet another shape and associate the yellow status with a diamond shape, but before doing anything further or participate in the discussion I like to hear your view, at the end of the day this is something LT has to support, and you guys have the final verdict here.

**Comment by limetech** [comment]
Yes we're giving this some thought.  Will discuss soon.

**Comment by limetech** [comment]
I think we have this finally sorted!
