### ISSUE TITLE
Duplicate generated NTP server entries in /etc/ntp.conf

### ISSUE THREAD

**Issue by eschultz** [limetech/dynamix#170]
At the bottom of /etc/ntp.conf you'll notice duplicate generated server blocks:

```
# Generated entries follow:
server pool.ntp.org iburst
# Generated entries follow:
server pool.ntp.org iburst
```

In the web ui, changing the NTP server 1 from `pool.ntp.org` to say `10.0.0.1` will update the bottom of /etc/ntp.conf to:

```
# Generated entries follow:
server pool.ntp.org iburst
# Generated entries follow:
server 10.0.0.1 iburst
```

**Comment by eschultz** [comment]
I think the issue is `rc.M` executes and appends one of the generated entry blocks and then it executes `rc.ntpd` which appends another generated entry block to `/etc/ntp.conf`

Safe to remove the code in rc.M that restores NTP configuration and leave it all up to rc.ntpd?

One discrepancy I noticed between the rc.M and rc.ntpd's NTP configuration handling was rc.M contained this extra bit:
```
  # restore previously stored drift file
  if [ -a /boot/config/drift ]; then
    mv /boot/config/drift /etc/ntp
  fi
```
Important?  I wasn't able to locate in any of the other scripts where /etc/ntp/drift was saved/persisted back to /boot/config/

**Comment by eschultz** [comment]
Oh, as a bonus for removing the ntp configuration code from rc.M you'll eliminate this error from showing during boot:

```
cp: cannot stat '/etc/ntp.conf-': No such file or directory
```

**Comment by limetech** [comment]
The bug is that the file "/etc/ntp.conf-" is missing from the release for some reason.
