### ISSUE TITLE
'yellow-xxx' icon

### ISSUE THREAD

**Issue by limetech** [limetech/dynamix#172]
bergware - wondering if you can find yellow-on icon where the icon itself stands out a bit more.  Maybe just a slightly more 'orange' look to it.  Even though color says "yellow" it really should be more orange.  The naming of the color was after traffic lights where people commonly call the middle, or warning signal "yellow" when it's really amber/orange.

**Comment by bergware** [comment]
Sure, made yellow more orange.

Also I enlarged the triangles and squares by 1 pixel for better visibility.

See my github pull request
