### ISSUE TITLE
"multipart/form-data" not supported by emhttp ?

### ISSUE THREAD

**Issue by bergware** [limetech/dynamix#178]
I have created a drag-and-drop feature for the user images. It allows a user to drag an image onto a user box and have the old/original picture replaced.

This function calls a PHP script to do the reception of the binary image file (POST) and it uses as content-type "multipart/form-data". emhttp however responds to this with an error 501: unsupported feature.

Anyway to have emhttp accept binary file uploads ?

**Comment by eschultz** [comment]
+1
I plan to implement something like that for the VM icon at some point so I
will run into the same pitfall.

**Comment by limetech** [comment]
The only post type emhttp accepts at this time is "application/x-www-form-urlencoded".  Let me look into this.

**Comment by bergware** [comment]
Indeed "application/x-www-form-urlencoded" is accepted, but doesn't allow binary files.

**Comment by jonpanozzo** [comment]
Drag and drop is fantastic in terms of making things easy and intuitive to use.

A few questions:

1 - File size / type restrictions?  What if someone tries to drag / drop a 40MB PSD file?
2 - Image size / editing?  If someone picks an image that doesn’t have an even ratio of width and height, how do we handle that?

**Comment by bergware** [comment]
I used the HTML5 variant, see http://tutorialzine.com/2011/09/html5-file-upload-jquery-php

But I needed to modify the script to make it work with multiple drop zones. I have that part working and you can simply drag a picture and drop on a user image to replace it, saving however is not possible yet due to a limitation in emhttp.

You can set limitations for file size, file type and number of files to prevent 'wrong' files to be copied. Also auto sizing is supported to have images displayed as 48x48 no matter the original.

**Comment by bergware** [comment]
Small caveat ... not all browsers support HTML5 drag-n-drop (MSIE is notoriously missing), user will get a message that the browser doesn't support the feature though.

**Comment by eschultz** [comment]
You can configure PHP to accept up to a maximum file upload size. Emhttp
will probably need to handle limiting the upload size (not sure if php's
upload size limit comes in to play with CLI).

I've used php gd functions pretty extensively so it can be used to open and
manipulate images on the fly. I might have to compile/enable this for php.
Psd files wouldn't open but jpg, gif and png would be fine for php to
manipulate. We could crop the image to a perfect square aspect if needed.

**Comment by jonpanozzo** [comment]
Between you and Ronald, sounds like you guys have this covered, but clearly there’s a piece that we’ll need Tom to look at and that’s emhttp.

**Comment by limetech** [comment]
Ok this is not going to be "quick and easy" to add to emhttp.  I have a multipart/form-data parser but passing data to php-cli might be an issue.  Maybe it's time to move to nginx?

**Comment by limetech** [comment]
A workaround would be to use "application/x-www-form-urlencoded" with the file data passed base64 encoded.

**Comment by eschultz** [comment]
Did somebody say Nginx?!?  :+1:  Getting me as excited as a kid in a candy store! :candy:

**Comment by bergware** [comment]
Will have a look at the base64 encoding, perhaps that can do...

More in favor of lighttpd, but nginx is cool too :)

Bit surprised though that emhttp does have support of multipart, it's around for quite some time.

**Comment by bergware** [comment]
Ok, I needed to write a javascript base64 conversion routine, and modified the filedrop script to do a 'regular' POST command and this is working.

I can save uploaded image files now :+1: 

Drag-n-drop is working, saving is working, last piece of the puzzle: a delete function to restore the default picture. Almost there!

**Comment by jonpanozzo** [comment]
Woo hoo!  Awesome work Ronald!  Can't wait to try all this out.  Think you
could replicate this under display settings so folks could upload their own
banner image too?

**Comment by bergware** [comment]
Got everything working now, works like a charm!

Should be doable for the banner too ...

**Comment by bergware** [comment]
Should add an image 'click' operation to open a file selection dialog next to the drag-n-drop feature.
