### ISSUE TITLE
Check network connectivity in unRAIDServer.plg

### ISSUE THREAD

**Issue by bergware** [limetech/dynamix#182]
Below a substitute function to check network connectivity, this approach pings the google DNS server, in doing so we check network connectivity outside the local network and avoid situation where local gateway won't respond to pings.

    # Wait until network is ready
      ip=8.8.4.4
      timer=30
      while [[ $timer -gt 0 ]]; do
        if [[ -n $(route -n|awk '/^0.0.0.0/{print $2}') && $(ping -qnc1 $ip|awk '/received/{print $4}') -eq 1 ]]; then
          break
        fi
        ((timer--))
        sleep 1
      done
      if [[ $timer -eq 0 ]]; then
        echo "No network communication !!!" &gt;&amp;2
        exit 1
      fi

Ps. Funny to see that *everybody* copies my 'old' network check :)

**Comment by limetech** [comment]
Nice, I added that to the unRAIDServer.plg file.  I was wondering *who* created that in the first place, wanted to give them a credit... should have known... :)

**Comment by bergware** [comment]
Ever wondered who introduced the ENTITY keywords in the PLG files ... now you know !!

**Comment by limetech** [comment]
I think I new that...

**Comment by limetech** [comment]
http://i.imgur.com/WrSwOcx.gifv
