### ISSUE TITLE
Update for rc.local

### ISSUE THREAD

**Issue by bergware** [limetech/dynamix#191]
I propose to add the following to rc.local

    # Needed by dynamix
    if [ -x /etc/rc.d/rc.cpuload ]; then
      echo "Starting cpuload daemon: /etc/rc.d/rc.cpuload"
      /etc/rc.d/rc.cpuload start
    fi
    --------------------------------
    # Copy monitor.ini file
    if [ -s /boot/config/plugins/dynamix/monitor.ini ]; then
      cp /boot/config/plugins/dynamix/monitor.ini /var/local/emhttp
      chmod -x /var/local/emhttp/monitor.ini
    fi

    # Copy custom banner
    if [ -s /boot/config/plugins/dynamix/banner.png ]; then
      cp /boot/config/plugins/dynamix/banner.png /usr/local/emhttp/webGui/images
      chmod -x /usr/local/emhttp/webGui/images/banner.png
    fi
    --------------------------------
    # Initialize notifications
    # /usr/local/sbin/notify init - not needed, please remove
    /usr/local/sbin/notify smtp-init
 
This allows stored threshold values for notifications to be restored upon system reboot
and load a custom banner upon system reboot

The *notify init* command is not needed and can be taken out.

**Comment by limetech** [comment]
Changes put into 6.1
