### ISSUE TITLE
networking info incorrect if only bridge

### ISSUE THREAD

**Issue by limetech** [limetech/dynamix#227]
In SystemInformation.php, there are checks for bond and eth interfaces.  But if there is a bridge defined, network info is reported through the bridge i/f (eg, 'br0').  That is, bond is 'above' physical 'eth', and bridge is above bond.

This results in:
eth0: not connected
eth1: not connected

Fix is to see what is the name of the bridge and then look for it in ifconfig -s.

This issue also affects the Dashboard Network display.

**Comment by bergware** [comment]
I had a look but all appears to work as should be, ethernet state is directly taken from the interface itself and doesn't depend on the presence of a bridge.

I am using the following settings:

Enable bonding = yes
Bonding mode = balance-alb (6)
Setup bridge = yes
Bridge name = br0
Bridge enable STP = yes
Bridge forward delay = 0
Obtain IP address automatically = no
Obtain DNS server address automatically = no

Anything different in your testing ?

**Comment by limetech** [comment]
Yes turn off bonding and you'll see what I mean.  Caution: if you have multiple NIC's in your server connected to your router, unplug all but one of them unless your router supports STP (else there will be an ARP-storm and it will bring down your entire network - yikes).

**Comment by bergware** [comment]
Don't worry networking is my professional territory, know all about spanning-tree and L2 loops, and yes we had once 50,000+ customers down due to a loop (bug) ...

**Comment by limetech** [comment]
That must have been a "fun" day.  I noticed when it happens on our little local LAN if you just unplug the ethernet port originating the ARP requests everything almost instantly goes back to normal.

**Comment by bergware** [comment]
Yeah, that surely was a lot of "fun", though Cisco didn't laugh that much ;)

I changed bonding to off with a single port (eth0) connected and all is still fine.

What output do you get from:
ethtool eth0
ethtool eth1

**Comment by bergware** [comment]
![image](https://cloud.githubusercontent.com/assets/5715228/9665661/f6583a9e-5271-11e5-88f6-619f5a288204.png)

**Comment by eschultz** [comment]
I noticed the same issue Tom was seeing on a few machines over here `eth0: not connected` and finally had a few minutes to look in to this.  There seems to be a grep regex regression between version 2.14 (in unRAID 6.1.x) and the latest grep version 2.22 (in unRAID 6.2).

With grep 2.22, this regex returns nothing (webgui is currently using this regex): 
`ethtool eth0 | grep -Po '^\s+(Speed|Duplex): \K[^U]+'`

I added `\n` to it and now it works properly in either version of grep:
`ethtool eth0 | grep -Po '^\s+(Speed|Duplex): \K[^U\n]+'`
returns:
`1000Mb/s`
`Full`

Ronald & Tom: does this new regex work well on your unRAID machines?  It's probably a good idea to update 6.1 branch just in-case grep is updated in Slackware 14.1 patches.

**Comment by limetech** [comment]
Yes this works but you have to escape the backslash in the string passed to exec():

`exec("ethtool $port|grep -Po '^\s+(Speed|Duplex): \K[^U\\n]+'",$info);`

**Comment by bergware** [comment]
There are two instances where this grep syntax is used: DashUpdate.php and SystemInformation.php

There are other similar expressions used as well, such as **... \K[^"]** wondering if these are impacted too, but need to check their presence.

**Comment by eschultz** [comment]
Thanks guys.  I think we can roll with this new regex for DashUpdate.php and SystemInformation.php (I'll submit a PR for this for 6.1 in a couple minutes)

I've done a little more testing and the expression **\K[^"]** , found in a couple places, seems to still work as expected.  As far as I can tell, the latest version of grep (perl-regex mode) fails to return when **\K** is used before a inverse-range (e.g. **[^U]**) and *only* when the regex would normally capture the rest of the line.
