### ISSUE TITLE
config - browsers auto completing fields resulting in changes

### ISSUE THREAD

**Issue by thezoggy** [limetech/dynamix#254]
config - browsers auto completing fields resulting in changes
all you need to do is add `autocomplete=false` to the forms you do not want this to happen to.
ideally you should have this off anytime there is a password field.. as this is the main thing that people tell their browsers to remember.. thus can cause the issue.

example:
https://lime-technology.com/forum/index.php?topic=46436.msg444952#msg444952

**Comment by eschultz** [comment]
Thanks @thezoggy, we'll look in to this and add `autocomplete=false` where necessary.
