### ISSUE TITLE
Proper way to add extra application-specific flags/parameters when creating docker container

### ISSUE THREAD

**Issue by kitce** [limetech/dynamix#269]
I found that the "Extra parameters" is appended before the "repository" in the final command, but I need to add some flags/parameters which are application-specific.

For example, I need to run `mongo` with `--auth` flag.
I can only do this by setting "repository" to `mongo --auth`.

This workaround is quite strange and not a good practice.

Will there be any update that supports application-specific parameters?

**Comment by gfjardim** [comment]
If you need to specify application parameters, you should use **Post Arguments** instead of **Extra Parameters**.

**Comment by kitce** [comment]
But where is "Post Arguments"?

I am using unRAID 6.3.5 and Dynamix webGUI 2017.05.26

**Comment by bergware** [comment]
You need unRAID 6.4
