### ISSUE TITLE
Scheduled parity check not started after reboot

### ISSUE THREAD

**Issue by bergware** [limetech/dynamix#34]
In the original webGui plugin I had this piece of code to add the parity check to the cron job

\# Create cron entry (if active)
entry=$(grep '^cron=' $cfg | cut -d'"' -f2)
if [ -n "$entry" ]; then
  cron=/tmp/parity.tmp
  crontab -l | grep -vi 'Scheduled Parity Check' | grep -v '/root/mdcmd check' > $cron
  echo '# Scheduled Parity Check' >> $cron
  echo "$entry" | cut -d"'" -f2 >> $cron
  crontab $cron
  rm -f $cron
fi

This ensures that the job is added upon reboot or re-installation. I guess we need some replacement solution to make it work in the new situation.

**Comment by eschultz** [comment]
This partially looks like what's included in your 'bandaid' in https://raw.githubusercontent.com/bergware/dynamix/master/unRAIDv6/dynamix.bandaid.plg?

**Comment by bergware** [comment]
Yeah the band-aid solution is more or less as above, but besides the scheduler it also adds cron jobs for notification monitoring, array health checks and plugin version checks.

These need to be included in a system start-up process somehow.

**Comment by limetech** [comment]
Here's an idea for how to handle crontab.  I created this script in /usr/local/sbin called update_cron:

```
#/bin/bash

# Concatenate the current set of plugin-specific cron files
# into single system crontab.

ENTRIES=$(cat /boot/config/plugins/*/*.cron 2>/dev/null)
if (($? != 0)); then
  crontab -c /etc/cron.d -d
else
  echo "$ENTRIES" | crontab -c /etc/cron.d -
fi
```

What you do is create .cron files in the plugin config directory on the flash and execute update_cron.  To remove a crontab entry you remove the .cron file and execute update_cron.

When emhttp initializes it will execute update_cron thereby restoring all the currently configured .cron files.

For example, since emhttp handles mover schedule I changed it write /boot/config/plugins/dynamix/mover.cron file.

In case of parity checker, I guess when user enables this feature via webGui it would result in creating /boot/config/plugins/dynamix/paritycheck.cron.  The existence of this file could be used determine if parity checker is enabled.

Same concept for other background scheduled jobs we might want to create.

What do you think, do it?

**Comment by bergware** [comment]
The concept looks okay, but you may want to take this a step further.

Create a wrapper which can manipulate the cron file. This would allow functions and plugins to create, modify and delete "their" cron file via a 'standard' method.

**Comment by limetech** [comment]
That's the point of having *.cron entries in the plugin config directory.  A plugin just needs to create the file and call update_cron.  I want to avoid directly modifying cron files and instead use 'crontab' command to handle this.  This is because dillon's cron maintains internal table and it works best to use crontab to manipulate files.  What I think we can do is invoke update_cron automatically via cron but haven't tried that yet.

**Comment by bergware** [comment]
I wasn't clear enough ...

With "cron file" I meant the file which is created under the plugins folder. Instead of relying on the plugin to put the file in the 'right' place, the wrapper takes care of this (similar as your parse_plugin_cfg wrapper).

**Comment by limetech** [comment]
The right place for any plugin is /boot/config/plugins/<plugin-name>/<filename>.cron

A plugin might have multiple .cron files, and/or a .cron file might have multiple entries.

**Comment by limetech** [comment]
Ok, I think I see what you mean, sure we could create a php wrapper function that does this.

The concept is that there isn't a central file that needs to be modified.

**Comment by bergware** [comment]
function parse_cron_cfg ($plugin, $text = "") {
  $cron = "/boot/config/plugins/$plugin/$plugin.cron";
  if ($text) file_put_contents($cron, $text); else @unlink($cron);
  exec("/usr/local/sbin/update_cron");
}

Create / modify
parse_cron_cfg ("my_plugin", "# Cron entry data\n * * * * * my_command\n")

Delete
parse_cron_cfg ("my_plugin")

**Comment by limetech** [comment]
function parse_cron_cfg ($plugin, $job, $text = "") {
$cron = "/boot/config/plugins/$plugin/$job.cron";
if ($text) file_put_contents($cron, $text); else @unlink($cron);
exec("/usr/local/sbin/update_cron");
}

Create / modify
parse_cron_cfg ("my_plugin", "mover", "# Cron entry data\n * * * * * my_command\n");
parse_cron_cfg ("my_plugin", "parity-check", "# Cron entry data\n * * * * * my_command\n");

**Comment by bergware** [comment]
yep, plugin may have multiple entries, good catch :)

**Comment by limetech** [comment]
The existence or non-existences of /boot/config/plugins/$plugin/$job can be used to determine if the corresponding feature is enabled or disabled.

**Comment by limetech** [comment]
It seems to work if I create "/boot/config/plugins/dynamix/update_cron.cron" that has this content:

*/1 * * * * /usr/local/sbin/update_cron

In this case you could get rid of 
 exec("/usr/local/sbin/update_cron");

Now any .cron file deposited in /boot/config/plugins/plugin-name will get scheduled after at most 2 minutes.

**Comment by bergware** [comment]
Wouldn't that unnecessarily calling the update_cron script every minute even when there no changes ?

**Comment by limetech** [comment]
Sure but in grand scheme of cpu cycles probably doesn't matter.  We don't have to do it, just an observation really.

**Comment by eschultz** [comment]
Could you use inotify events (add and remove) for any *.cron files off of /boot/config/plugins/* and fire off /usr/local/sbin/update_cron on any changes?

I haven't used inotify yet but it looked really simple to setup watches like that.

**Comment by limetech** [comment]
Yes I've been wanting to use inotify for a while now.  That could be added.  It's my understanding watches have to be put on specific files/directories, not a "wildcard", so that does add some complication.

**Comment by bergware** [comment]
I have updated several files to work with the 'new' cron method. That is looking good so far, will post the changes later on github.

The one thing I can not test is the 'mover' (I created the cron file for this manually so it gets included, but obviously this needs to be generated through the configuration page).

**Comment by bergware** [comment]
Sorry, accidentally removed my previous post ..

I have updated several files to work with the new 'cron' method. So far this is looking good, and I will update github in a later stage.

I can't test "mover" though, I did create the .cron file manually so it is part of the process, but obviously this needs to be done from the configuration page.

**Comment by limetech** [comment]
I already have '../webGui/mover.cron' implemented in -beta14.

**Comment by bergware** [comment]
One omission ...

In the startup process also the "monitor" script needs to be included. This means that a "monitor.cron" file needs to be created upon startup (if not already existing) with the following content:

# System monitoring - check every minute
*/1 * * * * /usr/local/sbin/monitor 1>/dev/null 2>&1

**Comment by limetech** [comment]
Here is how I think this should be handled:
* There should be a config setting that says something like "system monitor interval" and accepts a value from 0..N (seconds).
* The default value of this setting should be 0.
* When user sets this value non-zero, webGui creates the monitor.cron file with first entry "*/N" where N is the value.
* When user sets this value to zero, webGui deletes the monitor.cron file
* The webGui can check for and parse monitor.cron to establish "N" on startup.

This means that first time someone boots unRaid OS with this code, system monitoring will be turned off and they have to go turn it on if that's what they want.  But we can document this.

**Comment by bergware** [comment]
It probably is the easiest way to implement, the other "services" are started the same way. A disadvantage is that the user has to explicitely enable the monitoring, hence my question.

It should then be highlighted that by default NO monitoring at all takes place and the user has to configure that first.

A simple enable/disable selection will do in my opinion in this case. I will make an update which you can evaluate.

**Comment by limetech** [comment]
Ok, sounds good.

**Comment by bergware** [comment]
See pull request ...
