### ISSUE TITLE
Move now button shows up even if "use cache" is set to no.

### ISSUE THREAD

**Issue by jonpanozzo** [limetech/dynamix#38]
See post here:  http://lime-technology.com/forum/index.php?topic=36527.msg341416.msg#341416

Essentially if someone has the "use cache" function disabled, but they have a cache drive, that means they do not want the mover to be invoked.

I think johnodon from our forums isn't saying the mover is kicking in automatically in this situation, but it is disturbing him that he's getting the "move now" option from the array operation page. An accidental click there could do something undesirable.

Thoughts?

**Comment by bergware** [comment]
Display of the Mover button has been made conditional, this issue can be closed.
